site_name: Estima

theme:
    name: material
    language: 'pt'
    palette:
        primary: 'white'
    logo: 'favicon.png'

repo_name: 'Estima'
repo_url: 'https://github.com/desenho-2019'

plugins:
    - search
    - awesome-pages
