site_name: Cafofo

theme:
    name: material
    language: 'pt'
    palette:
        primary: 'cyan'
        accent: 'orange'
    logo: 'favicon.png'

repo_name: 'Cafofo'
repo_url: 'https://github.com/desenho-2019'

plugins:
    - search
    - awesome-pages
