site_name: Estima

theme:
    name: material
    language: 'pt'
    palette:
        primary: 'white'
    logo: 'favicon.png'

repo_name: 'Estima'
repo_url: 'https://desenho-2019.github.io/Wiki/'

plugins:
    - search
    - awesome-pages
